import "./globals.css";
import { Gabarito } from "next/font/google";
import { Navbar } from "../components/navbar/Navbar";
import { Footer } from "../components/footer/Footer";
import AuthProvider from "./providers/AuthProvider";

const gabarito = Gabarito({ subsets: ["latin"] });

export const metadata = {
  title: "AI UN Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gabarito.className}>
        <AuthProvider>
          <Navbar />
          <div className="container">
            <div className="wrapper">{children}</div>
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
