import "./globals.css";
import { Gabarito } from "next/font/google";
import { Navbar } from "../components/navbar/Navbar";
import { Footer } from "../components/footer/Footer";
import Newsletter from "@/components/newsletter/Newsletter";

const gabarito = Gabarito({ subsets: ["latin"] });

export const metadata = {
  title: "AI in Congress",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gabarito.className}>
          <Navbar />
          <Newsletter />
          <div className="container">
            <div className="wrapper">{children}</div>
          </div>
          <Footer />
      </body>
    </html>
  );
}
